version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build app
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Copy over SSH
          command: |
            rsync -r ~/project/dist $SSH_USER@$SSH_HOST:~
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "portfolio/deploy.sh"


workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
