version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/laszloborbely.com
          paths:
            - dist

workflows:
  build-and-deploy-workflow:
    jobs:
      - build
